apiVersion: v1
data:
  grafana.ini: "[analytics]\ncheck_for_updates = true \n[grafana_net]\nurl = https://grafana.net\n[log]\nmode
    = console\n[paths]\ndata = /var/lib/grafana/\nlogs = /var/log/grafana\nplugins
    = /var/lib/grafana/plugins\nprovisioning = /etc/grafana/provisioning\n[server]\ndomain
    = ''\n"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: monitoring-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 9.3.1
    helm.sh/chart: grafana-6.48.2
  name: monitoring-stack-grafana
  namespace: default