  apiVersion: monitoring.coreos.com/v1
  kind: Prometheus
  metadata:
    labels:
      app: kube-prometheus-stack-prometheus
      app.kubernetes.io/instance: monitoring-stack
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/part-of: kube-prometheus-stack
      app.kubernetes.io/version: 43.3.0
      chart: kube-prometheus-stack-43.3.0
      heritage: Helm
      release: monitoring-stack
    name: monitoring-stack-kube-prom-prometheus-2
    namespace: default
  spec:
    alerting:
      alertmanagers:
      - apiVersion: v2
        name: monitoring-stack-kube-prom-alertmanager
        namespace: default
        pathPrefix: /
        port: http-web
    enableAdminAPI: false
    evaluationInterval: 30s
    externalUrl: http://monitoring-stack-kube-prom-prometheus-2.default:9090
    hostNetwork: false
    image: quay.io/prometheus/prometheus:v2.40.5
    listenLocal: false
    logFormat: logfmt
    logLevel: info
    paused: false
    podMonitorNamespaceSelector: {}
    podMonitorSelector:
      matchLabels:
        release: monitoring-stack
    portName: http-web
    probeNamespaceSelector: {}
    probeSelector:
      matchLabels:
        release: monitoring-stack
    replicas: 1
    retention: 10d
    routePrefix: /
    ruleNamespaceSelector: {}
    ruleSelector:
      matchLabels:
        release: monitoring-stack
    scrapeInterval: 30s
    securityContext:
      fsGroup: 2000
      runAsGroup: 2000
      runAsNonRoot: true
      runAsUser: 1000
    serviceAccountName: monitoring-stack-kube-prom-prometheus
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelector:
      matchLabels:
        release: monitoring-stack
    shards: 1
    version: v2.40.5
    walCompression: true